on: [push]

jobs:
  reformat-sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Run the reformat action
      - name: Reformat SQL Files
        uses: credfeto/action-yaml-format@v1.3.1
      - name: Commit files
        run: |
          git config --local user.email "<githubusername>@users.noreply.github.com"
          git config --local user.name "YAML Reformat Bot"
          git commit --all -m"Reformat YAML Files to common format." || true
      - name: Push
        run: git push "https://${{github.actor}}:${{secrets.SOURCE_PUSH_TOKEN}}@github.com/${{github.repository}}.git" "HEAD:${{ env.GIT_BRANCH }}"